Models/ErrorViewModel.cs
using System;

namespace WorkshopBooking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/VehicleBooking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WorkshopBooking.Models
{
    public class VehicleBooking
    {
        public int Id { get; set; }
        [Required, Display(Name = "Client")]
        public string ClientName { get; set; }
        [Required, Display(Name = "Car")]
        public string ModelName { get; set; }
        
        [DataType(DataType.Date), Display(Name = "Booking Date")]
        public DateTime DateOfBooking { get; set; }
        [MaxLength(25), Required]
        public string Notes { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WorkshopBooking.Models;

namespace WorkshopBooking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

Controllers/VehicleBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkshopBooking.Data;
using WorkshopBooking.Models;

namespace WorkshopBooking.Controllers
{
    public class VehicleBookingsController : Controller
    {
        private readonly WorkshopBookingContext _context;

        public VehicleBookingsController(WorkshopBookingContext context)
        {
            _context = context;
        }

        // GET: VehicleBookings
        public async Task<IActionResult> Index(DateTime? BookingFilterDate)
        {
            return View(await _context.Vehicles.Where(x => BookingFilterDate == null || x.DateOfBooking >= BookingFilterDate).ToListAsync());
        }

        // GET: VehicleBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleBooking = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleBooking == null)
            {
                return NotFound();
            }

            return View(vehicleBooking);
        }

        // GET: VehicleBookings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleBookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClientName,ModelName,DateOfBooking,Notes")] VehicleBooking vehicleBooking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicleBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleBooking);
        }

        // GET: VehicleBookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleBooking = await _context.Vehicles.FindAsync(id);
            if (vehicleBooking == null)
            {
                return NotFound();
            }
            return View(vehicleBooking);
        }

        // POST: VehicleBookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClientName,ModelName,DateOfBooking,Notes")] VehicleBooking vehicleBooking)
        {
            if (id != vehicleBooking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicleBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleBookingExists(vehicleBooking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleBooking);
        }

        // GET: VehicleBookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleBooking = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleBooking == null)
            {
                return NotFound();
            }

            return View(vehicleBooking);
        }

        // POST: VehicleBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicleBooking = await _context.Vehicles.FindAsync(id);
            _context.Vehicles.Remove(vehicleBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleBookingExists(int id)
        {
            return _context.Vehicles.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Vehicle Booking App</h1>
</div>

<hr />
<div class="container">
    <button type="button" class="btn btn-secondary btn-lg btn-block" onclick="location.href='VehicleBookings'">View Bookings</button>
</div>

<hr />
<div class="container">
    <button type="button" class="btn btn-secondary btn-lg btn-block" onclick="location.href='VehicleBookings/Create'">Create Booking</button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkshopBooking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkshopBooking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WorkshopBooking 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/VehicleBookings/Create.cshtml
@model WorkshopBooking.Models.VehicleBooking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>VehicleBooking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelName" class="control-label"></label>
                <input asp-for="ModelName" class="form-control" />
                <span asp-validation-for="ModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBooking" class="control-label"></label>
                <input asp-for="DateOfBooking" class="form-control" />
                <span asp-validation-for="DateOfBooking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VehicleBookings/Delete.cshtml
@model WorkshopBooking.Models.VehicleBooking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleBooking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBooking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBooking)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/VehicleBookings/Details.cshtml
@model WorkshopBooking.Models.VehicleBooking

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VehicleBooking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBooking)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBooking)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/VehicleBookings/Edit.cshtml
@model WorkshopBooking.Models.VehicleBooking

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>VehicleBooking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelName" class="control-label"></label>
                <input asp-for="ModelName" class="form-control" />
                <span asp-validation-for="ModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBooking" class="control-label"></label>
                <input asp-for="DateOfBooking" class="form-control" />
                <span asp-validation-for="DateOfBooking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VehicleBookings/Index.cshtml
@model IEnumerable<WorkshopBooking.Models.VehicleBooking>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "VehicleBookings", FormMethod.Get))
{
  
    @Html.TextBox("BookingFilterDate", "Pick a date", new { @readonly = "readonly" })
    <input type="submit" value="Filter Bookings" />
}

<hr/>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModelName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBooking)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBooking)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />

@section scripts {
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#BookingFilterDate').datepicker();
        });
    </script>

}